## Sigmoid Function

In [1]:
import math 
def basic_Sigmoid(x):
    s = 1/ (1 + math.exp(-x))
    
    return s


## Sigmoid function with NumPy

In [7]:
import numpy as np 
x = np.array([1, 2, 3])

def sigmoid_Numpy(x):
    return 1/ (1 + np.exp(x))

In [8]:
sigmoid_Numpy(x)

array([0.26894142, 0.11920292, 0.04742587])

## Gradient Function 


In [9]:
def gradient(x):
    return sigmoid_Numpy(x) * (1 - sigmoid_Numpy(x))

In [10]:
gradient(x)

array([0.19661193, 0.10499359, 0.04517666])

## Reshapie Image Function 

In [16]:
def reshape_img(img): 
    return img.reshape(img.shape[0] * img.shape[1] * img.shape[2], 1)

image = np.array([[[0.468534, 0.456467, 0.657683],
                   [0.564675, 0.464534, 0.467654],
                   [0.245232, 0.685984, 0.569804]],
                  
                  [[0.468534, 0.456467, 0.657683],
                   [0.564675, 0.464534, 0.467654],
                   [0.245232, 0.685984, 0.569804]],
                  
                  [[0.468534, 0.456467, 0.657683],
                   [0.564675, 0.464534, 0.467654],
                   [0.245232, 0.685984, 0.569804]]])

reshaped_img = reshape_img(image)
print(reshaped_img)

[[0.468534]
 [0.456467]
 [0.657683]
 [0.564675]
 [0.464534]
 [0.467654]
 [0.245232]
 [0.685984]
 [0.569804]
 [0.468534]
 [0.456467]
 [0.657683]
 [0.564675]
 [0.464534]
 [0.467654]
 [0.245232]
 [0.685984]
 [0.569804]
 [0.468534]
 [0.456467]
 [0.657683]
 [0.564675]
 [0.464534]
 [0.467654]
 [0.245232]
 [0.685984]
 [0.569804]]


## Normalization Function 

In [17]:
def normalized(x): 
    norm = np.linalg.norm(x, axis =1, keepdims=True)
    return x/norm


## Softmax Function

In [21]:
def softmax(x): 
    x = np.exp(x)
    norm = np.linalg.norm(x, axis=1, keepdims= True)
    return x/norm
    
x= [[1, 2, 3, 4],
    [6, 7, 8, 9]]

print(softmax(x))

[[0.04630344 0.12586581 0.34213873 0.9300295 ]
 [0.04630344 0.12586581 0.34213873 0.9300295 ]]


## Dot Product and Timing

In [23]:
import time

x = [1, 6, 3, 5, 2, 7, 5, 7, 8, 2, 9, 3, 9, 3, 9, 5, 1, 8]
y = [3, 5, 2, 9, 6, 7, 2, 8, 5, 1, 9, 3, 0, 2, 4, 6, 8, 3]


start_time = time.process_time() 

dot = 0
for i in range(len(x)): 
    dot += x[i] * y[i]
    
end_time = time.process_time()

elapsed_time = 1000 * (end_time - start_time)

print(dot)
print(elapsed_time)

447
0.0
